name: .NET

on:
  push:
    branches: [ "move", "rotate" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x
      - name: Install dependencies
        run: dotnet restore ./SpaceBattle.Lib
      - name: Build
        run: dotnet build ./SpaceBattle.Lib --configuration Release --no-restore
      - name: Test
        run: dotnet test -p:CollectCoverage=true -p:CoverletOutput=coverage/ -p:CoverletOutputFormat=opencover
      - name: justls1
        run: ls SpaceBattle.Lib.Test
      - name: justls2
        run: ls 
      - name: justls3
        run: ls SpaceBattle.Lib
      - name: Codecov
        uses: codecov/codecov-action@v3
        with: 
          files: SpaceBattle.Lib.Test/coverage/coverage.info
