name: .NET

on:
  push:
    branches: [ "move", "rotate" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x
      - name: Install dependencies
        run: dotnet restore ./SpaceBattle.Lib
      - name: Build
        run: dotnet build ./SpaceBattle.Lib --configuration Release --no-restore
      - name: Test
        run: dotnet test -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=lcov --no-build --verbosity d ./SpaceBattle.Lib.Test
      - name: Publish coverage report to coveralls.io  
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: Game.Lib.Test/TestResults/coverage.info